cursos/urls.py
from django.urls import path
from . import views

app_name = 'cursos'

urlpatterns = [
    path('inicio/',views.inicio, name='inicio'),
    path('criar/',views.criar, name='criar-curso'),
    path('cursos/',views.buscar_cursos, name='buscar-cursos'),
    path('buscar/',views.buscar_cursos, name='buscar'),
    path('perfil/',views.perfil, name='perfil'),
    path('perfil/excluir-conta-confirm',views.excluir_conta_confirm, name='excluir-conta-confirm'),
    # path('perfil/excluir-conta',views.excluir_conta, name='excluir-conta'),
    path('perfil/mudar-senha',views.mudar_senha, name='mudar-senha'),
    path('<str:curso_slug>/resumo/',views.resumo, name='resumo'),
    path('<str:curso_slug>/',views.curso, name='curso'),
    path('<str:curso_slug>/criar-modulo/',views.criar_modulo, name='criar-modulo'),
    path('<str:curso_slug>/modulos/',views.modulos, name='modulos'), 
    path('<str:curso_slug>/alunos/',views.exibir_alunos, name='exibir-alunos'), 
    path('<str:curso_slug>/<int:modulo_id>/',views.exibir_modulo, name='exibir-modulo'),
    path('<str:curso_slug>/<int:modulo_id>/criar-post/',views.criar_post, name='criar-post'),
    path('<str:curso_slug>/<int:modulo_id>/criar-atividade/',views.criar_atividade, name='criar-atividade'),    
    path('<str:curso_slug>/<int:modulo_id>/<int:post_id>/',views.exibir_post, name='exibir-post'),
    path('<str:curso_slug>/<int:modulo_id>/<int:post_id>/adicionar-arquivo/',views.adicionar_arquivo, name='adicionar-arquivo'),
    
    path('<str:curso_slug>/<int:modulo_id>/<int:post_id>/adicionar-comentario/',views.adicionar_comentario, name='adicionar-comentario'), 
    path('<str:curso_slug>/<int:modulo_id>/<int:post_id>/respostas/',views.exibir_respostas, name='exibir-respostas'),
    path('<str:curso_slug>/<int:modulo_id>/<int:post_id>/respostas/<str:aluno>',views.exibir_resposta_de_aluno, name='exibir-resp-aluno'),
    path('<str:curso_slug>/mural/',views.mural, name='mural'),
    path('<str:curso_slug>/mural/adicionar-comentario/',views.adicionar_mensagem_mural, name='adicionar-mensagem'),
    
    path('<str:curso_slug>/config/',views.config_curso, name='config_curso'),
    path('<str:curso_slug>/config/deletar',views.deletar_curso, name='deletar_curso'),
]

genus/urls.py
from django.contrib import admin
from django.urls import include,path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('signup/',include('registro.urls'), name='registro'),
    path('genus/',include('cursos.urls'), name='inicio'),
    path('',views.homepage, name='home'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

registro/urls.py
from django.urls import path, include, reverse_lazy
from django.contrib.auth import views as auth_views
from . import views

app_name = 'registro'

urlpatterns = [
    path('', views.cadastro, name='cadastro'),
    path('logout/', views.user_logout, name='logout'),
    path('login/', views.user_login, name='login'),
    path('reset-password/', views.recuperar_senha, name='recuperar-senha'),
    path('check/', views.check, name="check"),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(success_url = reverse_lazy('registro:password_reset_complete')), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(success_url = reverse_lazy('registro:password_reset_done')), name='password_reset'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
     name='password_reset_complete'),
]

templates/addArquivo2.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/addArquivo2Style.css' %}">
    <title>Genus</title>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/168c8af039.js" crossorigin="anonymous"></script>
</head>
<body>
  <nav>
    <img src="{% static 'images/logo.svg' %}" alt="Genus Logo">
    <ul>
        <a href="{% url 'cursos:perfil' %}"><li><i class="far fa-user-circle"></i>Perfil</li></a> 
    </ul>
    <button class="exit-btn" onclick="location.href='{% url 'registro:logout' %}'"> SAIR </button>
    <div class="dropdown">
        <button class="dropbtn"><i class="fas fa-bars"></i></button>
        <div class="dropdown-content">
            <a href="{% url 'cursos:perfil' %}"><i class="far fa-user-circle"></i>Perfil</a>
            <a href="{% url 'registro:logout' %}"><i class="fas fa-sign-out-alt"></i>Sair</a>
        </div>
    </div>
    
</nav>
<div class="content">
    <header>
        <h1>Adicionar arquivo</h1>
    </header>
    <section>
      {% block content %}
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form1.as_p }}
        {% if form2 %}
          {{ form2.as_p }}
          <button type="submit" name="arquivo" value="arquivo">Adicionar arquivo</button>
        {% endif %}
      </form>
      {% endblock %}
    </section>
    
</div>
</body>
</html>

templates/addMensagem.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/addComentarioStyle.css' %}">
    <title>Genus</title>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/168c8af039.js" crossorigin="anonymous"></script>
</head>
<body>
  <nav>
    <img src="{% static 'images/logo.svg' %}" alt="Genus Logo">
    <ul>
        <a href="{% url 'cursos:perfil' %}"><li><i class="far fa-user-circle"></i>Perfil</li></a> 
    </ul>
    <button class="exit-btn" onclick="location.href='{% url 'registro:logout' %}'"> SAIR </button>
    <div class="dropdown">
        <button class="dropbtn"><i class="fas fa-bars"></i></button>
        <div class="dropdown-content">
            <a href="{% url 'cursos:perfil' %}"><i class="far fa-user-circle"></i>Perfil</a>
            <a href="{% url 'registro:logout' %}"><i class="fas fa-sign-out-alt"></i>Sair</a>
        </div>
    </div>
    
</nav>
<div class="content">
    <header>
        <h2>adicionar mensagem ao mural</h2>
    </header>
    <section>
      {% block content %}
      <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <button type="submit">enviar</button>
      </form>
      {% endblock %}
    </section>
    
</div>
</body>
</html>

templates/atividade.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Genus</title>
    <link rel="stylesheet" href="{% static 'css/atividadestyle.css' %}">
</head>
<body>
    
    <header>
        <div class="out-container">
            <a href="{% url 'cursos:inicio' %}" style="align-self: center;"><img src="{% static 'images/logo.svg' %}" alt="Genus Logo"></a>
            <nav class="overlay">
                 <ul>
                    <li><a href="{% url 'cursos:curso' curso.slug%}">Mural</a></li>
                    <li><a href="{% url 'cursos:modulos' curso.slug %}">Módulos e atividades</a></li>
                    <li><a href="{% url 'cursos:exibir-alunos' curso.slug %}">Alunos</a></li>
                    {% if dono %}
                        <li><a href="{% url 'cursos:config_curso' curso.slug %}">Configurações</a></li>
                    {% endif %}
                </ul>
            </nav>
              
        </div>
    </header>
        
    <div class="content-box">
        <h1>{{curso.title}}</h1>
        <!-- Atividade -->
        <div class="atividade">
            <div class="card-atividade">
                <h2>{{post}}</h2>
                <hr>
                <div class="atividade-content">
                    <p>{{post.description}}</p>
                    <br>
                    {% for content in contents_modulo %}
                        <ul class="content-item">
                            <li>{{content.item.render}}</li>
                        </ul>
                        <hr>
                    {% endfor %}
                </div>
                    <div class="buttons-tablet">
                        <!--  div tablet render funciona apenas para small screen -->
                        <div class="tablet-render">
                                {% if dono %}
                                    <button><a href="{% url 'cursos:adicionar-arquivo' curso.slug modulo.id post.id %}">Adicionar arquivos</a></button>
                                    <br>
                                {% else %}
                                    <button><a href="{% url 'cursos:adicionar-arquivo' curso.slug modulo.id post.id %}">Submeter resposta</a></button>
                                {% endif %}
                        </div>
                    </div>
                    
            </div>
            <div class="card-buttons">
                <h2>Conteúdo:</h2>
                <br>
                {% if dono %}
                   <button><a href="{% url 'cursos:adicionar-arquivo' curso.slug modulo.id post.id %}">Adicionar arquivos</a></button>
                   <br>
                {% else %}
                    <button><a href="{% url 'cursos:adicionar-arquivo' curso.slug modulo.id post.id %}">Submeter resposta</a></button>
                {% endif %}
            </div>
        </div>
        <br>

        <!-- Respostas -->
        <div class="answer">
            {% if dono %}
                <button><a href="{% url 'cursos:exibir-respostas' curso.slug modulo.id post.id %}">Visualizar todas respostas</a></button> 
            {% else %}
                <br>
                <h2>Sua resposta:</h2>
                <br>
                {% if respostas|length == 0 %}
                    <p>Você ainda não submeteu respostas</p>
                {% endif %}

                {% for content in respostas %}
                    <ul class="content-item">
                        <li><a href="">{{content.item.render}}</a></li>
                    </ul>
                {% endfor %}
                <hr>
            {% endif %}

            {% if not dono %}
                <div class="nota">
                    <h2>Sua nota:</h2>
                    <p>{{grade}}</p>
                </div>
            {% endif %}
        </div>

        <!-- Comentários -->
        <div class="container-comentarios">
            <h1>Comentários:</h1>
            <div class="comentarios">
                <div>
    
                    {% if not post.comments.all %}
                         <h2>Sem Comentários</h2>
                            <div class="buttons-comentarios">
                                <button> <a href="{% url 'cursos:adicionar-comentario' curso.slug modulo.id post.id %}">Adicionar Comentário</a></button>
                             </div>
                    {% else %}
                        {% for comment in post.comments.all %}
                            <div class="infoUser">
                                <h2>{{ comment.author }}</h2> 
                                <p>{{ comment.created_date}}</p>
                            </div>
                            <div class="comment-text">
                                <p>{{ comment.text }}</p>
                                <hr>
                            </div>
                        {% endfor %}
                            <div class="buttons-comentarios">
                                <button><a href="{% url 'cursos:adicionar-comentario' curso.slug modulo.id post.id %}">Adicionar Comentário</a></button>
                            </div>      
                    {% endif %}
                
            </div>
    
        </div>
    </div>

</body>
</html>

templates/createActivity.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/createActivityStyle.css' %}">
    <title>Genus</title>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/168c8af039.js" crossorigin="anonymous"></script>
</head>
<body>
  <nav>
    <img src="{% static 'images/logo.svg' %}" alt="Genus Logo">
    <ul>
        <a href="{% url 'cursos:perfil' %}"><li><i class="far fa-user-circle"></i>Perfil</li></a> 
    </ul>
    <button class="exit-btn" onclick="location.href='{% url 'registro:logout' %}'"> SAIR </button>
    <div class="dropdown">
        <button class="dropbtn"><i class="fas fa-bars"></i></button>
        <div class="dropdown-content">
            <a href="{% url 'cursos:perfil' %}"><i class="far fa-user-circle"></i>Perfil</a>
            <a href="{% url 'registro:logout' %}"><i class="fas fa-sign-out-alt"></i>Sair</a>
        </div>
    </div>
    
</nav>
<div class="content">
    <header>
        <h1>Criar atividade</h1>
    </header>
    <section>
      {% block content %}
      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="hidden" name="next" value="{{ redirect }}">
        <button type="submit">Criar</button>
      </form>
  {% endblock %}
    </section>
    
</div>
</body>
</html>

templates/createCurso.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/createCourseStyle.css' %}">
    <title>Genus</title>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/168c8af039.js" crossorigin="anonymous"></script>
</head>
<body>
  <nav>
    <a href="{% url 'cursos:inicio' %}"><img src="{% static 'images/logo.svg' %}" alt="Genus Logo"></a>
    <ul>
        <a href="{% url 'cursos:perfil' %}"><li><i class="far fa-user-circle"></i>Perfil</li></a> 
    </ul>
    <button class="exit-btn" onclick="location.href='{% url 'registro:logout' %}'"> SAIR </button>
    <div class="dropdown">
        <button class="dropbtn"><i class="fas fa-bars"></i></button>
        <div class="dropdown-content">
            <a href="{% url 'cursos:perfil' %}"><i class="far fa-user-circle"></i>Perfil</a>
            <a href="{% url 'registro:logout' %}"><i class="fas fa-sign-out-alt"></i>Sair</a>
        </div>
    </div>
    
</nav>
<div class="content">
    <header>
        <h1>Criar curso</h1>
    </header>
    <section>
      {% block content %}
      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Criar</button>
      </form>
      {% endblock %}
    </section>
    
</div>
</body>
</html>

templates/createModule.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/createCourseStyle.css' %}">
  <title>Genus</title>
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
  <script src="https://kit.fontawesome.com/168c8af039.js" crossorigin="anonymous"></script>
</head>
<body>
  <nav>
    <img src="{% static 'images/logo.svg' %}" alt="Genus Logo">
    <ul>
        <a href="{% url 'cursos:perfil' %}"><li><i class="far fa-user-circle"></i>Perfil</li></a> 
    </ul>
    <button class="exit-btn" onclick="location.href='{% url 'registro:logout' %}'"> SAIR </button>
    <div class="dropdown">
        <button class="dropbtn"><i class="fas fa-bars"></i></button>
        <div class="dropdown-content">
            <a href="{% url 'cursos:perfil' %}"><i class="far fa-user-circle"></i>Perfil</a>
            <a href="{% url 'registro:logout' %}"><i class="fas fa-sign-out-alt"></i>Sair</a>
        </div>
    </div>
  </nav>
  <div class="content">
    <header>
        <h1>Criar módulo</h1>
    </header>
    <section>
      {% block content %}
        <form method="post">
          {% csrf_token %}
          {{ form.as_p }}
          <input type="hidden" name="next" value="{{ redirect }}">
          <button type="submit">Criar</button>
        </form>
      {% endblock %}
    </section>
    
  </div> 
</body>
</html>

templates/createPost.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/createPostStyle.css' %}">
    <title>Genus</title>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/168c8af039.js" crossorigin="anonymous"></script>
</head>
<body>
  <nav>
    <img src="{% static 'images/logo.svg' %}" alt="Genus Logo">
    <ul>
        <a href="{% url 'cursos:perfil' %}"><li><i class="far fa-user-circle"></i>Perfil</li></a> 
    </ul>
    <button class="exit-btn" onclick="location.href='{% url 'registro:logout' %}'"> SAIR </button>
    <div class="dropdown">
        <button class="dropbtn"><i class="fas fa-bars"></i></button>
        <div class="dropdown-content">
            <a href="{% url 'cursos:perfil' %}"><i class="far fa-user-circle"></i>Perfil</a>
            <a href="{% url 'registro:logout' %}"><i class="fas fa-sign-out-alt"></i>Sair</a>
        </div>
    </div>
    
</nav>
<div class="content">
    <header>
      {% if isActivity == False %}
        <h1>Criar postagem</h1>
      {% else %}
        <h1>Criar postagem</h1>
      {% endif %} 
    </header>
    <section>
      {% block content %}
      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="hidden" name="next" value="{{ redirect }}">
        <button type="submit">Criar</button>
      </form>
      {% endblock %}
    </section>
    
</div>
</body>
</html>

templates/modulo.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/stylemodulo.css' %}">
    <script src="https://kit.fontawesome.com/168c8af039.js" crossorigin="anonymous"></script>
    <title>Genus</title>
</head>
<body>
    <header>
        <div class="out-container">
            <a href="{% url 'cursos:inicio' %}" style="align-self: center;"><img src="{% static 'images/logo.svg' %}" alt="Genus Logo"></a>
            <nav class="overlay">
                 <ul>
                    <li><a href="{% url 'cursos:curso' curso.slug%}">Mural</a></li>
                    <li><a href="{% url 'cursos:modulos' curso.slug %}">Módulos e atividades</a></li>
                    <li><a href="{% url 'cursos:exibir-alunos' curso.slug %}">Alunos</a></li>
                    {% if dono %}
                        <li><a href="{% url 'cursos:config_curso' curso.slug %}">Configurações</a></li>
                    {% endif %}
                </ul>
            </nav>
              
        </div>

    </header>

    <div class="content-box">
        <h1>{{curso.title}}</h1>

        <section class="modulo">
            
            <div class="moduloheader">
                
                    <h2>{{modulo.title}}</h2>
        
                    <div>
                        {% if dono %}
                            <div class="dropdown">
                                <button class="dropbtn">Adicionar conteúdo</button>
                                <div class="dropdown-content">
                                    <a href="{% url 'cursos:criar-atividade' curso.slug modulo.id %}">Atividade</a>
                                    <a href="{% url 'cursos:criar-post' curso.slug modulo.id %}">Post</a>
                                </div>
                            </div>
                        {% endif %}
                    </div>
            </div>

            <div class="content-container">

                <h2>Descrição do Modulo</h2>
                <p>{{modulo.description}}</p>
    
                <div class="atividades">
                        <h2>Atividades e Posts</h2>
                        <ul>
                            {% for p in posts %}
                                <li><a href="{% url 'cursos:exibir-post' curso.slug modulo.id p.id %}">{{p}}</a> </li>
                            {% endfor %}
                        </ul>
                </div>
            </div>
    
        </section>
        
    </div>

</body>
</html>

templates/modulosCurso.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/modulosCursostyle.css' %}">
    <title>Genus</title>
    <script src="https://kit.fontawesome.com/168c8af039.js" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <div class="out-container">
            <a href="{% url 'cursos:inicio' %}" style="align-self: center;"><img src="{% static 'images/logo.svg' %}" alt="Genus Logo"></a>
            <nav class="overlay">
                 <ul>
                    <li><a href="{% url 'cursos:curso' curso.slug%}">Mural</a></li>
                    <li><a href="{% url 'cursos:modulos' curso.slug %}">Módulos e atividades</a></li>
                    <li><a href="{% url 'cursos:exibir-alunos' curso.slug %}">Alunos</a></li>
                    {% if dono %}
                        <li><a href="{% url 'cursos:config_curso' curso.slug %}">Configurações</a></li>
                    {% endif %}
                </ul>
            </nav>
              
        </div>

    </header>
        
    <div class="content-box">
        <h1>{{curso.title}}</h1>

        <h1>Módulos e atividades</h1>
        <div class="button-header">
            {% if dono %}
                <button><a href="{% url 'cursos:criar-modulo' curso.slug %}"><i class="fas fa-plus fa-md"></i> Criar módulo</a></button>
            {% endif %}
        </div>

        <div class="modulo-container">
            <ul>
                {% for modulo in modulos %}
                    <li>
                        <section class="modulo">

                            <div class="content-container">

                                <h2><a href="{% url 'cursos:exibir-modulo' curso.slug modulo.id %}">{{modulo.title}}</a></h2> 
                                        
                                        <div class="atividades">
                                            {% for ap in atividades_posts %}
                                                {% if ap.module == modulo %}
                                                    <ul class="atividades-container">
                                                        {% for ap in atividades_posts %}
                                                            <a href="{% url 'cursos:exibir-post' curso.slug modulo.id p.id %}"><li>{{p}} </li></a>
                                                        {% endfor %}
                                                    </ul>
                                                {% endif %} 
                                            {% endfor %}
                                        </div>
                            </div>
                        </section>
                    </li>
                
                {% endfor %}
                
            </ul>
        </div>
        
    </div>

</body>
</html>

templates/muralCurso.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/muralcurso.css' %}">
    <title>Genus</title>
    <!-- Imports -->
    <script src="https://kit.fontawesome.com/168c8af039.js" crossorigin="anonymous"></script>

</head>
<body>

    <!-- Scripts-->
    <script>
        function messageText(){
            document.getElementById('message').style.height="150px";
            document.getElementById('group1').style.opacity="1";
            return 
        }

        function cancelMessage(){
            document.getElementById('message').style.height="auto";
            document.getElementById('group1').style.opacity="0";
            return
        }
    </script>

    <header>
        <div class="out-container">
            <div class="out-header">
                <h2>{{curso.title}}</h2>
                <div class="brand-img">
                    <img src="{% static 'images/logo.svg' %}" alt="Genus Logo">
                </div>

            </div>
            <nav class="overlay">
                 <ul>
                    <li><a href="{% url 'cursos:curso' curso.slug%}">Mural</a></li>
                    <li><a href="{% url 'cursos:modulos' curso.slug %}">Módulos e atividades</a></li>
                    <li><a href="{% url 'cursos:exibir-alunos' curso.slug %}">Alunos</a></li>
                    {% if dono %}
                        <li><a href="{% url 'cursos:config_curso' curso.slug %}">Configurações</a></li>
                    {% endif %}
                </ul>
            </nav>

        </div>

    </header>

  
    <div class="container">
        <div class="muralimg">
            <h1>{{curso.title}}</h1>
        </div>
        <div class="content-container">
            
            {% if not curso.mensagens.all %}
                         <h2>sem mensagens no mural</h2>
                            <div class="buttons-mensagem">
                                <button> <a href="{% url 'cursos:adicionar-mensagem' curso.slug%}">adicionar mensagem</a></button>
                             </div>
                    {% else %}
                    <button><a href="{% url 'cursos:adicionar-mensagem' curso.slug%}">adicionar mensagem</a></button><br/>
                        
                    {% for mensagem in curso.mensagens.all %}
                    <div class="card">
                        <div class="card-header">
                            <h1><i class="far fa-user fa-sm"></i></h1>
                            <div class="info">
                                <div class="infoUser">
                                    <span><b>{{ mensagem.author }}</b></span>
                                    <span><b><i>{{ mensagem.created_date }}</i> </b></span>
                                </div>
                                <a href="#"><i class="fas fa-ellipsis-v fa-lg"></i></a>
                            </div>
                        </div>
                        <div class="card-content">
                            <p>{{ mensagem.text }}</p>
                        </div>
                    </div>
                        {% endfor %}
                            <div class="buttons-mensagem">
                            
                            </div>      
                    {% endif %}
        </div>
    </div>


</body>
</html>

templates/testeNota.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Genus</title>
</head>
<body>
  {% block content %}
  <h2>Form Nota</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
  </form>
  {% endblock %}
  
</body>
</html>